drivers/dahdi: fix build with clang-16
clang-16 enables -Werror=incompatible-pointer-types (along with buch of
other warnings) by default, thus resulting in errors such as:

/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.c:272:20: error: incompatible function
      pointer types initializing 'int (*)(const struct device *, struct kobj_uevent_env *)' with an expression of type
      'int (struct device *, struct kobj_uevent_env *)' [-Wincompatible-function-pointer-types]
        .uevent         = span_uevent,
                          ^~~~~~~~~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.c:709:20: error: incompatible function
      pointer types initializing 'int (*)(const struct device *, struct kobj_uevent_env *)' with an expression of type
      'int (struct device *, struct kobj_uevent_env *)' [-Wincompatible-function-pointer-types]
        .uevent         = device_uevent,
                          ^~~~~~~~~~~~~
2 errors generated.

This is due the change in bus_type strcut made in upstream commit
https://github.com/torvalds/linux/commit/2a81ada32f0e584fc0c943e0d3a8c9f4fae411d6.
Where they make uevent take a const *, as the strcut should not be
modifying the device that is passed into it.

This patch modifes some of the fucntions parameter types, making dahdi
possible to be built with clang-16.

Bug: https://bugs.gentoo.org/906179
Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>